const fs = require('fs');

const htmlContent = `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Jobs Feed</title>
  </head>
  <body>
    <h1>Jobs Feed Placeholder</h1>
    <p>This is a placeholder HTML file generated by GitHub Actions.</p>
  </body>
</html>
`;

fs.writeFileSync('jobs.html', htmlContent);
