const fs = require('fs');

console.log("✅ Running build-jobs.js");

const htmlContent = `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Jobs Feed</title>
  </head>
  <body>
    <h1>Jobs Feed Placeholder</h1>
    <p>This file was generated by GitHub Actions.</p>
  </body>
</html>
`;

try {
  fs.writeFileSync('jobs.html', htmlContent);
  console.log("✅ jobs.html written successfully");
} catch (error) {
  console.error("❌ Error writing jobs.html:", error);
  process.exit(1);
}
